### ISSUE TITLE
Setup OAuth login

### ISSUE THREAD

**Issue by nicolopomini** [nicolopomini/Lost-Found#2]
L'utente, tramite due campi di testo per mail e password, effettua il login.
HTD: l’utente inserisce in due campi di testo la propria mail e la propria password. Se sono corrette si viene reindirizzati sulla pagina principale, altrimenti si riceve un messaggio di errore

**Comment by damiclem** [comment]
Per il login tramite google, leggetevi questa https://cloud.google.com/nodejs/getting-started/authenticate-users. 
@damianodallapiccola qui dovrebbe esserci un esempio valido, creato da google:
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/4-auth/lib/oauth2.js
